name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'Enter your EMAIL'
        required: true
      password:
        description: 'Enter your PASSWORD'
        required: true

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install
          rm -rf node_modules
          yarn install --frozen-lockfile

      - name: Install Playwright version 1.39.0
        run: npm install playwright@1.39.0

      - name: Install Chrome Browser for Playwright
        run: |
          npx playwright install-deps chromium
          npx playwright install chromium

      - name: Create .env file
        run: |
          echo "EMAIL=kristine12716@yahoo.com" >> .env
          echo "PASSWORD=***" >> .env
          shell: /bin/bash -e {0}

      - name: Verify .env file content
        run: cat .env

      - name: Run Playwright tests
        env:
          EMAIL: ${{ github.event.inputs.email }}
          PASSWORD: ${{ github.event.inputs.password }}
        run: |
          echo "Running tests with the provided credentials"
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
